### Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json
Accept-Language:EN

{
  "name": "Muzaffar",
  "surname": "Andaqulov",
  "phone": "+998995092376",
  "password": "1234"
}


### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "phone": "+998995092376",
  "password": "1234"
}


### Verification
GET http://localhost:8080/auth/verification/5
Accept-Language: EN


###  registration resend
GET http://localhost:8080/auth/registration/resend/+998995092376
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjAzMzYzNjAsImlkIjo3LCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiIrOTk4OTk5NDc2OTcwIiwiZXhwIjoxNzIwNjgxOTYwLCJpc3MiOiJGYXlzTWFya2V0In0.W0W6h6W3YVCOjN6QpYCr1a9hm1TwLkUuW8s5dGDDz0ehmixptz1pwk0kp26UGFmiu3LHkvfh8IBY-QtUXNw55Q
