### Registration
POST http://localhost:8080/api/v1/authorization/registration
Content-Type: application/json

{
  "phone": "+998942702363",
  "password": "1234"
}

### Login
POST http://localhost:8080/api/v1/authorization/login
Content-Type: application/json

{
  "phone": "+998942702363",
  "password": "1234"
}


### Verification
GET http://localhost:8080/api/v1/authorization/verification/1


###  registration resend
GET http://localhost:8080/api/v1/authorization/registration/resend/+998942702363
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA2MTIxMTEsImlkIjoxLCJyb2xlIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiIrOTk4OTQyNzAyMzYzIiwiZXhwIjoxNzIwOTU3NzExLCJpc3MiOiJGYXlzTWFya2V0In0.-c7uzefisGjqrNOGmYk-HgsMMxTQSEWELRPGC-k9eCNgj29zRtEdVVfA8Gu7r0F8gEx0p1T-1vvvjWAmhMfkGg
