###
POST http://localhost:8080/api/v1/contracts/contractCreate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjE0NzcwMjEsImlkIjoxMCwicm9sZSI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiKzk5ODk5NTA5MjM3NiIsImV4cCI6MTcyMTgyMjYyMSwiaXNzIjoiRmF5c01hcmtldCJ9.3aGwr2RJN8SOEPAeUJVPUm9WFdSfY9c5fAFv1XXk0lcxlfWWUXSzgvLlQPHSCDNMU2bgCZzVt7jAcf5TXd3e3w

{
  "productName": "laptop",
  "name": "Alish",
  "surname": "Alishev",
  "scarf": "Alishevich",
  "productPrice": 3000000,
  "monthlyPayment": 250000,
  "phone": "+998999476970",
  "theRestIndebtedness": 0,
  "timeDayMonthYear": "2024-07-08T13:28:36.598020100"
}
